# Generated by Django 6.0.7 on 2026-07-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo_producto', models.CharField(choices=[('montura', 'Montura'), ('cristal_terminado', 'Cristal Terminado'), ('bloque_tallado', 'Bloque Tallado'), ('accesorio', 'Accesorio')], max_length=20, verbose_name='tipo de producto')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('codigo_modelo', models.CharField(max_length=100, verbose_name='código del modelo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('indice_refraccion', models.CharField(blank=True, default='', max_length=10, verbose_name='índice de refracción')),
                ('material', models.CharField(blank=True, default='', max_length=50, verbose_name='material')),
                ('tratamiento', models.CharField(blank=True, default='', max_length=50, verbose_name='tratamiento')),
                ('diseno', models.CharField(blank=True, default='', max_length=50, verbose_name='diseño')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='código de barras')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='color')),
                ('tamano', models.CharField(blank=True, default='', max_length=50, verbose_name='tamaño')),
                ('esfera', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='esfera')),
                ('cilindro', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='cilindro')),
                ('eje', models.IntegerField(blank=True, null=True, verbose_name='eje')),
                ('adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='adición')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('alerta_stock_minimo', models.IntegerField(default=5, verbose_name='alerta stock mínimo')),
                ('precio_al_mayor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio al mayor')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio de costo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventory.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'variante de producto',
                'verbose_name_plural': 'variantes de producto',
                'db_table': 'variantes_producto',
            },
        ),
    ]
