# Generated by Django 6.0.7 on 2026-07-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('tipo_producto', 'nombre'), name='categorias_unicas_tipo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='variantes_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('alerta_stock_minimo__gte', 0)), name='variantes_alerta_stock_minimo_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_al_mayor__gte', 0)), name='variantes_precio_mayor_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_costo__gte', 0)), name='variantes_precio_costo_no_negativo'),
        ),
    ]
