# Generated by Django 6.0.7 on 2026-08-21 22:04

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_categoria_activo_varianteproducto_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['search_vector'], name='productos_search_vector_idx'),
        ),
    ]
