# Generated by Django 6.0.7 on 2026-08-21 22:04

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_producto_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='productos_search_vector_gin_idx'),
        ),
    ]
