# Generated by Django 6.0.7 on 2026-08-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_producto_productos_search_vector_gin_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='idx_prod_search_vec',
            old_name='productos_search_vector_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='idx_prod_search_gin',
            old_name='productos_search_vector_gin_idx',
        ),
    ]
