# Generated by Django 6.0.7 on 2026-08-27 17:12

import backend.common.utils.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_productos_search_vector_idx_idx_prod_search_vec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marcas',
            },
            bases=(backend.common.utils.mixins.SanitizedModelMixin, models.Model),
        ),
    ]
