# Generated by Django 6.0.7 on 2026-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('orden_trabajo', 'Orden de Trabajo'), ('nota_entrega', 'Nota de Entrega'), ('recibo_pago', 'Recibo de Pago')], max_length=20, unique=True, verbose_name='tipo de documento')),
                ('contenido_html', models.TextField(verbose_name='contenido HTML')),
                ('estilos_css', models.TextField(blank=True, default='', verbose_name='estilos CSS')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'plantilla de documento',
                'verbose_name_plural': 'plantillas de documentos',
                'db_table': 'plantillas_documentos',
            },
        ),
    ]
