# Generated by Django 6.0.7 on 2026-08-24 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('categoria', models.CharField(choices=[('institucional', 'Institucional / Legal'), ('recursos_humanos', 'Recursos Humanos'), ('financiero', 'Financiero / Contable'), ('operativo', 'Operativo / Taller'), ('otro', 'Otro')], default='institucional', max_length=30, verbose_name='categoría')),
                ('archivo', models.FileField(upload_to='documentos_empresa/', verbose_name='archivo')),
                ('extension', models.CharField(blank=True, default='', max_length=15, verbose_name='extensión')),
                ('tamano_bytes', models.BigIntegerField(default=0, verbose_name='tamaño en bytes')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='versión')),
                ('es_plantilla_generable', models.BooleanField(default=False, verbose_name='es plantilla generable')),
                ('variables_schema', models.JSONField(blank=True, default=list, verbose_name='esquema de variables')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_empresa_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'documento de empresa',
                'verbose_name_plural': 'documentos de empresa',
                'db_table': 'documentos_empresa',
                'ordering': ['-creado_en'],
            },
        ),
    ]
