# Generated by Django 6.0.7 on 2026-07-30 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True, verbose_name='nombre de usuario')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(blank=True, default='', max_length=150, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, default='', max_length=150, verbose_name='apellido')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('vendedor_b2b', 'Vendedor B2B'), ('almacen', 'Almacén'), ('tecnico_taller', 'Técnico de Taller'), ('contabilidad', 'Contabilidad')], default='vendedor_b2b', max_length=20, verbose_name='rol')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(max_length=100, verbose_name='acción')),
                ('tabla_afectada', models.CharField(max_length=100, verbose_name='tabla afectada')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('detalles', models.JSONField(blank=True, null=True, verbose_name='detalles')),
                ('direccion_ip', models.CharField(blank=True, default='', max_length=45, verbose_name='dirección IP')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'db_table': 'registros_auditoria',
            },
        ),
    ]
