# Generated by Django 6.0.7 on 2026-08-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('desactivar', 'Desactivar'), ('ajuste_stock', 'Ajuste de stock'), ('confirmar_pedido', 'Confirmar pedido'), ('cambiar_estado', 'Cambiar estado'), ('cancelar_pedido', 'Cancelar pedido'), ('eliminar_pedido', 'Eliminar pedido'), ('aprobar_pago', 'Aprobar pago'), ('rechazar_pago', 'Rechazar pago'), ('asiento_libro_mayor', 'Asiento de libro mayor'), ('generar_documento', 'Generar documento')], max_length=100, verbose_name='acción'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='tabla_afectada',
            field=models.CharField(choices=[('usuarios', 'Usuarios'), ('clientes_optica', 'Clientes'), ('categorias', 'Categorías'), ('productos', 'Productos'), ('variantes_producto', 'Variantes'), ('recetas_opticas', 'Recetas ópticas'), ('pedidos', 'Pedidos'), ('detalles_pedido', 'Detalles de pedido'), ('contador_pedidos', 'Contador de pedidos'), ('metodos_pago', 'Métodos de pago'), ('pagos', 'Pagos'), ('libro_mayor', 'Libro mayor'), ('plantillas_documentos', 'Plantillas de documentos'), ('registros_auditoria', 'Registros de auditoría')], max_length=100, verbose_name='tabla afectada'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['-creado_en', '-id'], name='auditoria_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['tabla_afectada', 'objeto_id'], name='auditoria_tabla_objeto_idx'),
        ),
    ]
