# Generated by Django 6.0.7 on 2026-08-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registroauditoria_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='tabla_afectada',
            field=models.CharField(choices=[('usuarios', 'Usuarios'), ('clientes_optica', 'Clientes'), ('categorias', 'Categorías'), ('productos', 'Productos'), ('variantes_producto', 'Variantes'), ('recetas_opticas', 'Recetas ópticas'), ('pedidos', 'Pedidos'), ('detalles_pedido', 'Detalles de pedido'), ('contador_pedidos', 'Contador de pedidos'), ('metodos_pago', 'Métodos de pago'), ('pagos', 'Pagos'), ('libro_mayor', 'Libro mayor'), ('plantillas_documentos', 'Plantillas de documentos'), ('documentos_empresa', 'Documentos de empresa'), ('registros_auditoria', 'Registros de auditoría')], max_length=100, verbose_name='tabla afectada'),
        ),
    ]
