# Generated by Django 6.0.7 on 2026-07-30 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaOptica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(blank=True, default='', max_length=100, verbose_name='nombre del paciente')),
                ('od_esfera', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='OD esfera')),
                ('od_cilindro', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='OD cilindro')),
                ('od_eje', models.IntegerField(blank=True, null=True, verbose_name='OD eje')),
                ('od_adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='OD adición')),
                ('oi_esfera', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='OI esfera')),
                ('oi_cilindro', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='OI cilindro')),
                ('oi_eje', models.IntegerField(blank=True, null=True, verbose_name='OI eje')),
                ('oi_adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='OI adición')),
                ('distancia_pupilar', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='distancia pupilar')),
                ('notas', models.TextField(blank=True, default='', verbose_name='notas')),
            ],
            options={
                'verbose_name': 'receta óptica',
                'verbose_name_plural': 'recetas ópticas',
                'db_table': 'recetas_opticas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_pedido', models.CharField(max_length=20, unique=True, verbose_name='número de pedido')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('en_taller', 'En Taller'), ('listo_para_despacho', 'Listo para Despacho'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='subtotal')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='total')),
                ('notas', models.TextField(blank=True, default='', verbose_name='notas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.clienteoptica', verbose_name='cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('receta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.recetaoptica', verbose_name='receta')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio total')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.varianteproducto', verbose_name='variante')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'detalle de pedido',
                'verbose_name_plural': 'detalles de pedido',
                'db_table': 'detalles_pedido',
            },
        ),
    ]
