# Generated by Django 6.0.7 on 2026-08-01 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0002_categoria_activo_varianteproducto_activo_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.IntegerField(default=0, verbose_name='último número')),
            ],
            options={
                'verbose_name': 'contador de pedidos',
                'verbose_name_plural': 'contador de pedidos',
                'db_table': 'contador_pedidos',
            },
        ),
        migrations.AddField(
            model_name='recetaoptica',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_idx_estado'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='detalles_cantidad_positiva'),
        ),
    ]
