# Generated by Django 6.0.7 on 2026-07-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('moneda', models.CharField(default='USD', max_length=10, verbose_name='moneda')),
                ('requiere_referencia', models.BooleanField(default=True, verbose_name='requiere referencia')),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='tasa de cambio')),
                ('numero_referencia', models.CharField(blank=True, default='', max_length=100, verbose_name='número de referencia')),
                ('comprobante_imagen_url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL comprobante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('fecha_pago', models.DateTimeField(verbose_name='fecha de pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.clienteoptica', verbose_name='cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.metodopago', verbose_name='método de pago')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='LibroMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_asiento', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10, verbose_name='tipo de asiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='saldo posterior')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.clienteoptica', verbose_name='cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.pedido', verbose_name='pedido')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.pago', verbose_name='pago')),
            ],
            options={
                'verbose_name': 'libro mayor',
                'verbose_name_plural': 'libro mayor',
                'db_table': 'libro_mayor',
            },
        ),
    ]
