# Generated by Django 6.0.7 on 2026-08-01 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('finance', '0001_initial'),
        ('orders', '0002_contadorpedido_recetaoptica_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromayor',
            name='asiento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.libromayor', verbose_name='asiento origen'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_rechazo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='motivo de rechazo'),
        ),
        migrations.AddIndex(
            model_name='libromayor',
            index=models.Index(fields=['cliente', 'creado_en'], name='libro_mayor_idx_cliente_creado'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['pedido', 'estado'], name='pagos_idx_pedido_estado'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_cambio__gt', 0)), name='pago_tasa_cambio_positiva'),
        ),
    ]
