# Generated by Django 6.0.7 on 2026-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteOptica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('razon_social', models.CharField(max_length=150, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='nombre comercial')),
                ('identificacion_fiscal', models.CharField(max_length=30, unique=True, verbose_name='identificación fiscal')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(max_length=30, verbose_name='teléfono')),
                ('direccion', models.TextField(verbose_name='dirección')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='límite de crédito')),
                ('dias_credito', models.IntegerField(default=0, verbose_name='días de crédito')),
            ],
            options={
                'verbose_name': 'cliente óptica',
                'verbose_name_plural': 'clientes ópticas',
                'db_table': 'clientes_optica',
            },
        ),
    ]
