# Generated by Django 6.0.7 on 2026-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clienteoptica_dias_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteoptica',
            name='direccion',
            field=models.TextField(blank=True, default='', verbose_name='dirección'),
        ),
    ]
